<?php
# This file was automatically generated by the MediaWiki 1.23.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Kizoo";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogo = "$wgStylePath/common/images/wiki.png";
$wgLogo = "$wgStylePath/common/images/cloud.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@kizoo.azurewebsites.net";
$wgPasswordSender = "apache@kizoo.azurewebsites.net";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "ja-cdbr-azure-east-a.cloudapp.net";
$wgDBname = "KizooDB";
$wgDBuser = "b9c2773ad0ed32";
$wgDBpassword = "0d21820a";

# MySQL specific settings
$wgDBprefix = "kizoo_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "9144ce485dcf6f10bc5078dab66454af9ab0c553100da10e1c8465c16b9b8851";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "8818217f74433045";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";



# End of automatically generated settings.
# Add more configuration options below.


require_once("$IP/extensions/WindowsAzureSDK/WindowsAzureSDK.php");
require_once("$IP/extensions/WindowsAzureStorage/WindowsAzureStorage.php");

// extensions by Jaewoo
//require_once("$IP/extensions/CharInsert/CharInsert.php");
require_once("$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");
require_once("$IP/extensions/Cite/Cite.php");
$wgCiteEnablePopups = true;
//

$wgFileBackends[] = array(
		'name'        => 'azure-backend',
		'class'       => 'WindowsAzureFileBackend',
		'lockManager' => 'nullLockManager',
		'azureAccount'   => 'kizoo',
		'azureKey'       => 'mzr1h5nZX82XjceGP6VFSdcP+8jdHTF5mC8XqV5L1beXO++KRjBM2exYJeDkVYr1aNtL0Tn2EMUXXiXn61nXdQ==',

		//IMPORTANT: Mind the container naming conventions! http://msdn.microsoft.com/en-us/library/dd135715.aspx
		'wikiId'       => 'kizoo',
		'containerPaths' => array(
				'media-public'  => 'media-public',
				'media-thumb'   => 'media-thumb',
				'media-deleted' => 'media-deleted',
				'media-temp'    => 'media-temp',

		)
);

$wgLocalFileRepo = array (
	'class'             => 'LocalRepo',
	'name'              => 'local',
	'scriptDirUrl'      => '/php/mediawiki-filebackend-azure',
	'scriptExtension'   => '.php',
	'url'               => $wgScriptPath.'/img_auth.php', // It is important to set this to img_auth. Basically, there is no alternative.
	'hashLevels'        => 2,
	'thumbScriptUrl'    => false,
	'transformVia404'   => false,
	'deletedHashLevels' => 3,
	'backend'           => 'azure-backend',
	'zones' => 
			array (
					'public' => 
							array (
								'container' => 'local-public',
								'directory' => '',
							),
					'thumb' => 
							array(
								'container' => 'local-public',
								'directory' => 'thumb',
							),
					'deleted' => 
							array (
								'container' => 'local-public',
								'directory' => 'deleted',
							),
					'temp' => 
							array(
								'container' => 'local-public',
								'directory' => 'temp',
							)
		)
);

$wgImgAuthPublicTest = false;

// + by Jaewoo
$wgFileExtensions[] = 'zip';
$wgFileExtensions[] = 'doc';
$wgFileExtensions[] = 'xls';
$wgFileExtensions[] = 'pdf';
$wgFileExtensions[] = 'mp3';
$wgFileExtensions[] = 'svg';

$wgExternalLinkTarget = '_blank'; // 링크 누르면 새창으로
$wgAllowExternalImages = true;

$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

